### ISSUE TITLE
Works fine, but formatting is being ignored.

### ISSUE THREAD

**Issue by BlauweStadTechnologieen** [marcanuy/django-dynamic-breadcrumbs#7]
Works fine, but the following `def` function is being ignored

`    def remove_dashes(self):
        page_name = str(item)
        return self.page_name.replace('-',' ')`

**Comment by marcanuy** [comment]
That function does not exists in this repo.

**Comment by BlauweStadTechnologieen** [comment]
Ah ok, I must be suffering from that mental illness that causes you to have visions to non-existent code then. Awful disease, that....
