### ISSUE TITLE
is there simplest way to remove "alert alert-success" ?

### ISSUE THREAD

**Issue by buoncri** [marcanuy/django-dynamic-breadcrumbs#8]
What can be the simplest way to remove "alert alert-success" of the line:
```
 <ol class="breadcrumb alert alert-success" itemprop="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
```
thanks

**Comment by marcanuy** [comment]
The simplest way is to copy `dynamic_breadcrumbs/breadcrumbs.html` and edit the template as you like, then include that version of the template.

    {% include "custom_breadcrumbs.html" with breadcrumbs=breadcrumbs%}
